apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 612070058498.dkr.ecr.ap-south-1.amazonaws.com/dev/java
        ports:
        - containerPort: 80
