apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate :
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: my-pod-red
      labels:
        app: myapp
    spec:
      containers: 
        - name: my-co-red
          image: 612070058498.dkr.ecr.ap-south-1.amazonaws.com/dev/java:latest
          ports:
            - containerPort: 80